### ISSUE TITLE
How to get All Data when Paginator is set to true.

### ISSUE THREAD

**Issue by amandeep33** [prototype-berlin/loopback-paginator#6]
By default, When paginator is set to true, the response of get methods comes back as an object containing data and meta tags. The data is paginated by default.
Okay what if I want whole data only and no pagination info with it.
I think it should not override the response format unless we pass "?page=1" in url.
For eg. Let an api for Brands.

1. when I pass url **/brands** : It should return whole data as paginator=false returns.
2. when I pass url **/brands?page=1** : only then data must be in the format as paginator=true returns

**Comment by mahnuh** [comment]
@amandeep33 I just published a beta of loopback-paginator. Please run `npm i loopback-paginator@beta` and verify if everything works fine. I am currently not able to test it myself, as I am pretty busy.

**Comment by amandeep33** [comment]
@mahnuh I tested this. Now response is fine in both cases. But in first case when no page parameter is passed, data is still paginated i.e, 10 records only.

**Comment by mahnuh** [comment]
@amandeep33 please try v2.0.0-beta.1

**Comment by amandeep33** [comment]
@mahnuh I am still getting same results i.e, 10 records only.

**Comment by mahnuh** [comment]
@amandeep33 I just tested it and it works fine. I published v2.0.0 to npm. Please make sure you have the correct version installed (`npm i loopback-paginator@2.0.0`).

**Comment by amandeep33** [comment]
@mahnuh It's working fine now. Thanks for such quick enhancement.
